"use client";

import Image from "next/image";
import { useState } from "react";

interface State {
  id: number;
  state: string;
}

export default function Home() {
  const [state, setState] = useState<Array<State>>([
    { id: 1, state: "none" },
    { id: 2, state: "none" },
    { id: 3, state: "none" },
    { id: 4, state: "none" },
    { id: 5, state: "none" },
    { id: 6, state: "none" },
    { id: 7, state: "none" },
    { id: 8, state: "none" },
    { id: 9, state: "none" },
    { id: 10, state: "none" },
    { id: 11, state: "none" },
    { id: 12, state: "none" },
    { id: 13, state: "none" },
    { id: 14, state: "none" },
    { id: 15, state: "none" },
    { id: 16, state: "none" },
    { id: 17, state: "none" },
    { id: 18, state: "none" },
    { id: 19, state: "none" },
    { id: 20, state: "none" },
    { id: 21, state: "none" },
    { id: 22, state: "none" },
    { id: 23, state: "none" },
    { id: 24, state: "none" },
    { id: 25, state: "none" },
    { id: 26, state: "none" },
    { id: 27, state: "none" },
    { id: 28, state: "none" },
    { id: 29, state: "none" },
    { id: 30, state: "none" },
    { id: 31, state: "none" },
    { id: 32, state: "none" },
    { id: 33, state: "none" },
    { id: 34, state: "none" },
    { id: 35, state: "none" },
    { id: 36, state: "none" },
    { id: 37, state: "none" },
    { id: 38, state: "none" },
    { id: 39, state: "none" },
    { id: 40, state: "none" },
    { id: 41, state: "none" },
    { id: 42, state: "none" },
    { id: 43, state: "none" },
    { id: 44, state: "none" },
    { id: 45, state: "none" },
    { id: 46, state: "none" },
    { id: 47, state: "none" },
    { id: 48, state: "none" },
    { id: 49, state: "none" },
    { id: 50, state: "none" },
    { id: 51, state: "none" },
    { id: 52, state: "none" },
    { id: 53, state: "none" },
    { id: 54, state: "none" },
    { id: 55, state: "none" },
    { id: 56, state: "none" },
    { id: 57, state: "none" },
    { id: 58, state: "none" },
    { id: 59, state: "none" },
    { id: 60, state: "none" },
    { id: 61, state: "none" },
    { id: 62, state: "none" },
    { id: 63, state: "none" },
    { id: 64, state: "none" },
    { id: 65, state: "none" },
    { id: 66, state: "none" },
    { id: 67, state: "none" },
    { id: 68, state: "none" },
    { id: 69, state: "none" },
    { id: 70, state: "none" },
    { id: 71, state: "none" },
    { id: 72, state: "none" },
    { id: 73, state: "none" },
    { id: 74, state: "none" },
    { id: 75, state: "none" },
    { id: 76, state: "none" },
    { id: 77, state: "none" },
    { id: 78, state: "none" },
    { id: 79, state: "none" },
    { id: 80, state: "none" },
    { id: 81, state: "none" },
    { id: 82, state: "none" },
    { id: 83, state: "none" },
    { id: 84, state: "none" },
    { id: 85, state: "none" },
    { id: 86, state: "none" },
    { id: 87, state: "none" },
    { id: 88, state: "none" },
    { id: 89, state: "none" },
    { id: 90, state: "none" },
    { id: 91, state: "none" },
    { id: 92, state: "none" },
    { id: 93, state: "none" },
    { id: 94, state: "none" },
    { id: 95, state: "none" },
    { id: 96, state: "none" },
    { id: 97, state: "none" },
    { id: 98, state: "none" },
    { id: 99, state: "none" },
    { id: 100, state: "none" },
    { id: 101, state: "none" },
    { id: 102, state: "none" },
    { id: 103, state: "none" },
    { id: 104, state: "none" },
    { id: 105, state: "none" },
    { id: 106, state: "none" },
    { id: 107, state: "none" },
    { id: 108, state: "none" },
    { id: 109, state: "none" },
    { id: 110, state: "none" },
    { id: 111, state: "none" },
    { id: 112, state: "none" },
    { id: 113, state: "none" },
    { id: 114, state: "none" },
    { id: 115, state: "none" },
    { id: 116, state: "none" },
    { id: 117, state: "none" },
    { id: 118, state: "none" },
    { id: 119, state: "none" },
    { id: 120, state: "none" },
    { id: 121, state: "none" },
    { id: 122, state: "none" },
    { id: 123, state: "none" },
    { id: 124, state: "none" },
    { id: 125, state: "none" },
    { id: 126, state: "none" },
    { id: 127, state: "none" },
    { id: 128, state: "none" },
    { id: 129, state: "none" },
    { id: 130, state: "none" },
    { id: 131, state: "none" },
    { id: 132, state: "none" },
    { id: 133, state: "none" },
    { id: 134, state: "none" },
    { id: 135, state: "none" },
    { id: 136, state: "none" },
    { id: 137, state: "none" },
    { id: 138, state: "none" },
    { id: 139, state: "none" },
    { id: 140, state: "none" },
    { id: 141, state: "none" },
    { id: 142, state: "none" },
    { id: 143, state: "none" },
    { id: 144, state: "none" },
    { id: 145, state: "none" },
    { id: 146, state: "none" },
    { id: 147, state: "none" },
    { id: 148, state: "none" },
    { id: 149, state: "none" },
    { id: 150, state: "none" },
    { id: 151, state: "none" },
    { id: 152, state: "none" },
    { id: 153, state: "none" },
    { id: 154, state: "none" },
    { id: 155, state: "none" },
    { id: 156, state: "none" },
    { id: 157, state: "none" },
    { id: 158, state: "none" },
    { id: 159, state: "none" },
    { id: 160, state: "none" },
    { id: 161, state: "none" },
    { id: 162, state: "none" },
    { id: 163, state: "none" },
    { id: 164, state: "none" },
    { id: 165, state: "none" },
    { id: 166, state: "none" },
    { id: 167, state: "none" },
    { id: 168, state: "none" },
    { id: 169, state: "none" },
    { id: 170, state: "none" },
    { id: 171, state: "none" },
    { id: 172, state: "none" },
    { id: 173, state: "none" },
    { id: 174, state: "none" },
    { id: 175, state: "none" },
    { id: 176, state: "none" },
    { id: 177, state: "none" },
    { id: 178, state: "none" },
    { id: 179, state: "none" },
    { id: 180, state: "none" },
    { id: 181, state: "none" },
    { id: 182, state: "none" },
    { id: 183, state: "none" },
    { id: 184, state: "none" },
    { id: 185, state: "none" },
    { id: 186, state: "none" },
    { id: 187, state: "none" },
    { id: 188, state: "none" },
    { id: 189, state: "none" },
    { id: 190, state: "none" },
    { id: 191, state: "none" },
    { id: 192, state: "none" },
    { id: 193, state: "none" },
    { id: 194, state: "none" },
    { id: 195, state: "none" },
    { id: 196, state: "none" },
    { id: 197, state: "none" },
    { id: 198, state: "none" },
    { id: 199, state: "none" },
    { id: 200, state: "none" },
    { id: 201, state: "none" },
    { id: 202, state: "none" },
    { id: 203, state: "none" },
    { id: 204, state: "none" },
    { id: 205, state: "none" },
    { id: 206, state: "none" },
    { id: 207, state: "none" },
    { id: 208, state: "none" },
    { id: 209, state: "none" },
    { id: 210, state: "none" },
    { id: 211, state: "none" },
    { id: 212, state: "none" },
    { id: 213, state: "none" },
    { id: 214, state: "none" },
    { id: 215, state: "none" },
    { id: 216, state: "none" },
    { id: 217, state: "none" },
    { id: 218, state: "none" },
    { id: 219, state: "none" },
    { id: 220, state: "none" },
    { id: 221, state: "none" },
    { id: 222, state: "none" },
    { id: 223, state: "none" },
    { id: 224, state: "none" },
    { id: 225, state: "none" },
    { id: 226, state: "none" },
    { id: 227, state: "none" },
    { id: 228, state: "none" },
    { id: 229, state: "none" },
    { id: 230, state: "none" },
    { id: 231, state: "none" },
    { id: 232, state: "none" },
    { id: 233, state: "none" },
    { id: 234, state: "none" },
    { id: 235, state: "none" },
    { id: 236, state: "none" },
    { id: 237, state: "none" },
    { id: 238, state: "none" },
    { id: 239, state: "none" },
    { id: 240, state: "none" },
    { id: 241, state: "none" },
    { id: 242, state: "none" },
    { id: 243, state: "none" },
    { id: 244, state: "none" },
    { id: 245, state: "none" },
    { id: 246, state: "none" },
    { id: 247, state: "none" },
    { id: 248, state: "none" },
    { id: 249, state: "none" },
    { id: 250, state: "none" },
    { id: 251, state: "none" },
    { id: 252, state: "none" },
    { id: 253, state: "none" },
    { id: 254, state: "none" },
    { id: 255, state: "none" },
    { id: 256, state: "none" },
    { id: 257, state: "none" },
    { id: 258, state: "none" },
    { id: 259, state: "none" },
    { id: 260, state: "none" },
    { id: 261, state: "none" },
    { id: 262, state: "none" },
    { id: 263, state: "none" },
    { id: 264, state: "none" },
    { id: 265, state: "none" },
    { id: 266, state: "none" },
    { id: 267, state: "none" },
    { id: 268, state: "none" },
    { id: 269, state: "none" },
    { id: 270, state: "none" },
    { id: 271, state: "none" },
    { id: 272, state: "none" },
    { id: 273, state: "none" },
    { id: 274, state: "none" },
    { id: 275, state: "none" },
    { id: 276, state: "none" },
    { id: 277, state: "none" },
    { id: 278, state: "none" },
    { id: 279, state: "none" },
    { id: 280, state: "none" },
    { id: 281, state: "none" },
    { id: 282, state: "none" },
    { id: 283, state: "none" },
    { id: 284, state: "none" },
    { id: 285, state: "none" },
    { id: 286, state: "none" },
    { id: 287, state: "none" },
    { id: 288, state: "none" },
    { id: 289, state: "none" },
    { id: 290, state: "none" },
    { id: 291, state: "none" },
    { id: 292, state: "none" },
    { id: 293, state: "none" },
    { id: 294, state: "none" },
    { id: 295, state: "none" },
    { id: 296, state: "none" },
    { id: 297, state: "none" },
    { id: 298, state: "none" },
    { id: 299, state: "none" },
    { id: 300, state: "none" },
    { id: 301, state: "none" },
    { id: 302, state: "none" },
    { id: 303, state: "none" },
    { id: 304, state: "none" },
    { id: 305, state: "none" },
    { id: 306, state: "none" },
    { id: 307, state: "none" },
    { id: 308, state: "none" },
    { id: 309, state: "none" },
    { id: 310, state: "none" },
    { id: 311, state: "none" },
    { id: 312, state: "none" },
    { id: 313, state: "none" },
    { id: 314, state: "none" },
    { id: 315, state: "none" },
    { id: 316, state: "none" },
    { id: 317, state: "none" },
    { id: 318, state: "none" },
    { id: 319, state: "none" },
    { id: 320, state: "none" },
    { id: 321, state: "none" },
    { id: 322, state: "none" },
    { id: 323, state: "none" },
    { id: 324, state: "none" },
    { id: 325, state: "none" },
    { id: 326, state: "none" },
    { id: 327, state: "none" },
    { id: 328, state: "none" },
    { id: 329, state: "none" },
    { id: 330, state: "none" },
    { id: 331, state: "none" },
    { id: 332, state: "none" },
    { id: 333, state: "none" },
    { id: 334, state: "none" },
    { id: 335, state: "none" },
    { id: 336, state: "none" },
    { id: 337, state: "none" },
    { id: 338, state: "none" },
    { id: 339, state: "none" },
    { id: 340, state: "none" },
    { id: 341, state: "none" },
    { id: 342, state: "none" },
    { id: 343, state: "none" },
    { id: 344, state: "none" },
    { id: 345, state: "none" },
    { id: 346, state: "none" },
    { id: 347, state: "none" },
    { id: 348, state: "none" },
    { id: 349, state: "none" },
    { id: 350, state: "none" },
    { id: 351, state: "none" },
    { id: 352, state: "none" },
    { id: 353, state: "none" },
    { id: 354, state: "none" },
    { id: 355, state: "none" },
    { id: 356, state: "none" },
    { id: 357, state: "none" },
    { id: 358, state: "none" },
    { id: 359, state: "none" },
    { id: 360, state: "none" },
    { id: 361, state: "none" },
    { id: 362, state: "none" },
    { id: 363, state: "none" },
    { id: 364, state: "none" },
    { id: 365, state: "none" },
    { id: 366, state: "none" },
    { id: 367, state: "none" },
    { id: 368, state: "none" },
    { id: 369, state: "none" },
    { id: 370, state: "none" },
    { id: 371, state: "none" },
    { id: 372, state: "none" },
    { id: 373, state: "none" },
    { id: 374, state: "none" },
    { id: 375, state: "none" },
    { id: 376, state: "none" },
    { id: 377, state: "none" },
    { id: 378, state: "none" },
    { id: 379, state: "none" },
    { id: 380, state: "none" },
    { id: 381, state: "none" },
    { id: 382, state: "none" },
    { id: 383, state: "none" },
    { id: 384, state: "none" },
    { id: 385, state: "none" },
    { id: 386, state: "none" },
    { id: 387, state: "none" },
    { id: 388, state: "none" },
    { id: 389, state: "none" },
    { id: 390, state: "none" },
    { id: 391, state: "none" },
    { id: 392, state: "none" },
    { id: 393, state: "none" },
    { id: 394, state: "none" },
    { id: 395, state: "none" },
    { id: 396, state: "none" },
    { id: 397, state: "none" },
    { id: 398, state: "none" },
    { id: 399, state: "none" },
    { id: 400, state: "none" },
  ]);
  const [turn, setTrun] = useState<Boolean>(false);

  const putPiece = (item: State): void => {
    if (item.state === "none") {
      setState((prev) => {
        return [...prev].map((prevItem) => {
          if (prevItem.id === item.id) {
            return {
              id: item.id,
              state: turn ? "black" : "white",
            };
          } else {
            return prevItem;
          }
        });
      });
      setTrun(!turn);
    }
  };

  return (
    <main className="bg-slate-800">
      <div className="flex flex-wrap content-center w-[1000px] m-auto h-screen">
        {state.map((item) => (
          <button key={item.id} onClick={() => putPiece(item)}>
            <Image
              src={"/" + item.state + ".svg"}
              alt="黒"
              width={50}
              height={50}
              priority
            ></Image>
          </button>
        ))}
      </div>
      <div className="fixed flex flex-row top-8 left-8 m-auto py-2 px-5 items-center rounded-xl bg-slate-800 bg-opacity-50">
        <h3 className="text-white mr-3 font-semibold">次は</h3>
        <Image
          src={"/" + (turn ? "black" : "white") + "_piece.svg"}
          alt="黒"
          width={40}
          height={40}
          priority
        ></Image>
      </div>
    </main>
  );
}
